name: Deploy to Firebase Hosting

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: oraichain/infra
          event-type: firebase
          client-payload: '{"ref": "${{ github.ref }}", "repo": "${{ github.repository }}", "node_version": "18", "target": "ton-bridge"}'